services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_PASSWORD=${DB_PASS?Variable not set}
    expose:
      - ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 10
  
  redis:
    image: redis/redis-stack-server:7.4.0-v5
    container_name: redis
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 10s
      retries: 10

  chromadb:
    image: chromadb/chroma:1.0.12
    container_name: chromadb
    expose:
      - ${CHROMADB_PORT}
    restart: unless-stopped
    volumes:
      - chroma_data:/chroma/chroma
      - ./chromadb_config.yaml:/config.yaml
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/${CHROMADB_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    restart: always
    command: server /data --address :${MINIO_API_PORT} --console-address :${MINIO_CONSOLE_PORT}
    ports:
      - ${MINIO_API_PORT}:${MINIO_API_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s

  docs_api:
    build:
      context: ./docs_api
      dockerfile: Dockerfile.docs_api
    env_file:
      - .env
    environment: &minio-env
      MINIO_ENDPOINT: ${MINIO_DOMAIN}:${MINIO_API_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    container_name: docs_api
    expose:
      - ${DOCS_API_PORT}
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port ${DOCS_API_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_healthy
      minio:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    environment:
      <<: *minio-env
    container_name: backend
    restart: always
    volumes:
      - ./backend/migrations/versions:/app/migrations/versions
    expose:
      - ${BACKEND_PORT}
    depends_on:
      - docs_api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_URL: "https://${SERVER_DOMAIN}/api"
        REACT_APP_API_FRONT_URL: "https://${SERVER_DOMAIN}"
    container_name: frontend
    volumes:
      - nginx_certs:/etc/nginx/certs
    ports:
      - "444:443"
    restart: always
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4:9.6
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 40
    restart: always
    ports:
    - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  pgadmin_data:
  nginx_certs:
  chroma_data:
  minio_data:
