"""empty message

Revision ID: 8e9bef4523d9
Revises: 05619f660e52
Create Date: 2025-09-04 05:56:45.552800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9bef4523d9'
down_revision: Union[str, None] = '05619f660e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('test_answers_log', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('test_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('test_answers_log', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('qa_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
