"""empty message

Revision ID: d9c3736fb6d5
Revises: ff1cb730dfcd
Create Date: 2025-07-11 06:20:55.371529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c3736fb6d5'
down_revision: Union[str, None] = 'ff1cb730dfcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'documents', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
